# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Highway to Root
tagline:          'Raise your knowledge'
description:      '...because everybody needs to know how deep the rabbit-hole goes.'
url:              https://highwaytoroot.github.io
baseurl:          /

author:
  name:           'Michele Campobasso, Jacopo Cortellazzi, Andrea Melis'
  url:            https://highwaytoroot.github.io

# Custom vars

github:
  repo:           https://github.com/highwaytoroot/highwaytoroot.github.io/

gems: [jekyll-paginate]
paginate: 100 # It is not a big number, but lets check if fixes the issue
paginate_path: "/htb/page:num"

# Extra setup for GitHub
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

pagination:
  
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true